### ISSUE TITLE
Might not work on localhost

### ISSUE THREAD

**Issue by TryingToImprove** [shystruk/no-internet#2]
It seems that it checks /favicon.ico .. If it is local development, it will not be able to detect router issues..

**Comment by shystruk** [comment]
@TryingToImprove 
You can pass url key and it will go directly to that.
Doc - https://github.com/shystruk/no-internet#url

```javascript
noInternet({ url: 'https://github.com/favicon.ico' })
```

**Comment by batistafrancis** [comment]
It's not useful! Any url can be off any time.

**Comment by shystruk** [comment]
Any suggestions?

**Comment by batistafrancis** [comment]
I don't know. I'm looking for that.

**Comment by shystruk** [comment]
Pass you app url, no another solution :)
