### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by stasyurkanis** [shystruk/no-internet#24]
Hey!
Seems that your package isn't working with ie11, is it?

**Comment by stasyurkanis** [comment]
I suppose you have the same problem https://github.com/sindresorhus/public-ip/issues/16

**Comment by shystruk** [comment]
Hi @stasyurkanis 
Thanks for reporting that. Will fix soon 👍

**Comment by shystruk** [comment]
@stasyurkanis use the latest version 1.6.0
