### ISSUE TITLE
[docs] let's notify users that this program won't work in Node

### ISSUE THREAD

**Issue by revelt** [shystruk/no-internet#4]
Let's update the readme to notify that this package won't work on Node:

<img width="309" alt="node" src="https://user-images.githubusercontent.com/8344688/69654407-a9d45a00-106c-11ea-8844-105b9bb242c1.png">

there is no `window` in Node!

It will work only in browser environment. It's important because most people come to npm for Node, not front-end packages and this package pops up at the top.

**Comment by shystruk** [comment]
@revelt Good point. Thanks for the feedback!
Updated the doc.
